import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Tanja Korolainen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="yanone-kaffeesatz-yanone"
      >
        {children}
      </body>
    </html>
  );
}
